### ISSUE TITLE
stupid

### ISSUE THREAD

**Issue by ansiya123** [BOYCOTTT/foss1#5]
never do this again . we will kill you ,stupid owner

**Comment by krishak** [comment]
u stupid monkey face

**Comment by ansiya123** [comment]
bloody erapppsssssssssssss

**Comment by FathimaShanaNoory** [comment]
it is not a issue babe.

**Comment by amar4u30** [comment]
get out idiot

**Comment by ansiya123** [comment]
thanku miss

**Comment by ansiya123** [comment]
onn podappa

**Comment by amar4u30** [comment]
onnu podiii

**Comment by FathimaShanaNoory** [comment]
hey guyzz, what are you doing?. our company will quit if we are irresponsible.

**Comment by krishak** [comment]
# onnu mindadirikoooo

**Comment by krishak** [comment]
u are absolutly correct noory
